AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating Dynamodb table


Parameters:
  HashKeyElementName:
    Type: String
    Default: CustomerId
    Description: Hash Key Name 


  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type



Resources:
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Customer
      AttributeDefinitions:
        -
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType

      KeySchema:
        -
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5  
